version: '3'
services:
  mysqldb:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3305"
  web:
    build: .
    command: bash -c "cd /opt/BHT-EMR-API && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 8000"
    volumes:
      - .:/opt
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
    links:
      - mysqldb:mysqldb